### ISSUE TITLE
cyipopt for mac os with M1 chip

### ISSUE THREAD

**Issue by pollinico** [conda-forge/cyipopt-feedstock#45]
### Comment:

Hi,

I cannot install with conda install -c conda-forge cyipopt.

I have a mac os with M1 chip. I run miniconda for osx-arm64 architecture. Is there a package for this architecture?

Do you have tips in case?

Thank you!

**Comment by moorepants** [comment]
I assume that conda forge updates all feedstocks to support new architectures. I don't know if that is something we control at the feedstock level. Maybe this feedstock hasn't been updated yet.

**Comment by moorepants** [comment]
It looks like the mac arm chips are experimentally supported by conda forge: https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by moorepants** [comment]
Seems to have worked, the binaries should be available in an hour or so. Closed with #46

**Comment by pollinico** [comment]
thanks a lot!!! i will try it out!

**Comment by pollinico** [comment]
It works beautifully!
Thanks a lot for the kind help!
